CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200603020239_InitialCreate') THEN
    CREATE TABLE all_guild_time_zones (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        guild text NULL,
        timezone_id text NULL,
        operating_system text NULL,
        CONSTRAINT "PK_all_guild_time_zones" PRIMARY KEY (id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200603020239_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200603020239_InitialCreate', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200819194156_Create_Events_Table') THEN
    ALTER TABLE all_guild_time_zones ALTER COLUMN guild TYPE numeric(20,0);
    ALTER TABLE all_guild_time_zones ALTER COLUMN guild SET NOT NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200819194156_Create_Events_Table') THEN
    CREATE TABLE all_guild_events (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        CONSTRAINT "PK_all_guild_events" PRIMARY KEY (id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200819194156_Create_Events_Table') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200819194156_Create_Events_Table', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200819225721_CreateScheduledEventsTable') THEN
    CREATE TABLE all_guild_scheduled_events (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        CONSTRAINT "PK_all_guild_scheduled_events" PRIMARY KEY (id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200819225721_CreateScheduledEventsTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200819225721_CreateScheduledEventsTable', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200819230759_FixAccidentalOmissions') THEN
    ALTER TABLE all_guild_scheduled_events ADD guild_event_id integer NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200819230759_FixAccidentalOmissions') THEN
    ALTER TABLE all_guild_scheduled_events ADD scheduled_date timestamp without time zone NOT NULL DEFAULT TIMESTAMP '0001-01-01 00:00:00';
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200819230759_FixAccidentalOmissions') THEN
    ALTER TABLE all_guild_events ADD event_description text NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200819230759_FixAccidentalOmissions') THEN
    ALTER TABLE all_guild_events ADD event_name text NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200819230759_FixAccidentalOmissions') THEN
    ALTER TABLE all_guild_events ADD guild numeric(20,0) NOT NULL DEFAULT 0.0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200819230759_FixAccidentalOmissions') THEN
    CREATE INDEX "IX_all_guild_scheduled_events_guild_event_id" ON all_guild_scheduled_events (guild_event_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200819230759_FixAccidentalOmissions') THEN
    ALTER TABLE all_guild_scheduled_events ADD CONSTRAINT "FK_all_guild_scheduled_events_all_guild_events_guild_event_id" FOREIGN KEY (guild_event_id) REFERENCES all_guild_events (id) ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200819230759_FixAccidentalOmissions') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200819230759_FixAccidentalOmissions', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200822192600_AddChannelId') THEN
    ALTER TABLE all_guild_scheduled_events ADD channel_id numeric(20,0) NOT NULL DEFAULT 0.0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200822192600_AddChannelId') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200822192600_AddChannelId', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200829224118_RemoveGuildTimeZonesAndAddUserTimeZones') THEN
    DROP TABLE all_guild_time_zones;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200829224118_RemoveGuildTimeZonesAndAddUserTimeZones') THEN
    CREATE TABLE all_user_time_zones (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        user_id numeric(20,0) NOT NULL,
        timezone_id text NULL,
        operating_system text NULL,
        CONSTRAINT "PK_all_user_time_zones" PRIMARY KEY (id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200829224118_RemoveGuildTimeZonesAndAddUserTimeZones') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200829224118_RemoveGuildTimeZonesAndAddUserTimeZones', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200910031424_AddPrefixAndDeletedFlag') THEN
    ALTER TABLE all_guild_scheduled_events ADD announced boolean NOT NULL DEFAULT FALSE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200910031424_AddPrefixAndDeletedFlag') THEN
    CREATE TABLE all_guild_prefixes (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        prefix text NULL,
        guild_id numeric(20,0) NOT NULL,
        CONSTRAINT "PK_all_guild_prefixes" PRIMARY KEY (id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200910031424_AddPrefixAndDeletedFlag') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200910031424_AddPrefixAndDeletedFlag', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201003194413_RemoveScheduledEvents') THEN
    DROP TABLE all_guild_scheduled_events;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201003194413_RemoveScheduledEvents') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201003194413_RemoveScheduledEvents', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201031033510_AddUserCardsAndKarmaRecords') THEN
    CREATE TABLE all_guild_background_jobs (
        hangfire_job_id text NOT NULL,
        guild_id numeric(20,0) NOT NULL,
        job_name text NULL,
        scheduled_time timestamp without time zone NOT NULL,
        job_type integer NOT NULL,
        CONSTRAINT "PK_all_guild_background_jobs" PRIMARY KEY (hangfire_job_id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201031033510_AddUserCardsAndKarmaRecords') THEN
    CREATE TABLE all_user_cards (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        user_id numeric(20,0) NOT NULL,
        user_timezone_id integer NOT NULL,
        CONSTRAINT "PK_all_user_cards" PRIMARY KEY (id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201031033510_AddUserCardsAndKarmaRecords') THEN
    CREATE TABLE all_user_guild_karma_records (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        user_id numeric(20,0) NOT NULL,
        guild_id numeric(20,0) NOT NULL,
        current_karma_amount numeric(20,0) NOT NULL,
        CONSTRAINT "PK_all_user_guild_karma_records" PRIMARY KEY (id)
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201031033510_AddUserCardsAndKarmaRecords') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201031033510_AddUserCardsAndKarmaRecords', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

