// <auto-generated />
using System;
using HandyHansel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HandyHansel.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    [Migration("20200819230759_FixAccidentalOmissions")]
    partial class FixAccidentalOmissions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0-preview.7.20365.15");

            modelBuilder.Entity("HandyHansel.Models.GuildEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("EventDesc")
                        .HasColumnType("text")
                        .HasColumnName("event_description");

                    b.Property<string>("EventName")
                        .HasColumnType("text")
                        .HasColumnName("event_name");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild");

                    b.HasKey("Id");

                    b.ToTable("all_guild_events");
                });

            modelBuilder.Entity("HandyHansel.Models.GuildTimeZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<decimal>("Guild")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("text")
                        .HasColumnName("operating_system");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text")
                        .HasColumnName("timezone_id");

                    b.HasKey("Id");

                    b.ToTable("all_guild_time_zones");
                });

            modelBuilder.Entity("HandyHansel.Models.ScheduledEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("GuildEventId")
                        .HasColumnType("integer")
                        .HasColumnName("guild_event_id");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scheduled_date");

                    b.HasKey("Id");

                    b.HasIndex("GuildEventId");

                    b.ToTable("all_guild_scheduled_events");
                });

            modelBuilder.Entity("HandyHansel.Models.ScheduledEvent", b =>
                {
                    b.HasOne("HandyHansel.Models.GuildEvent", "Event")
                        .WithMany()
                        .HasForeignKey("GuildEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
