# This is a basic workflow to help you get started with Actions

name: Deploy to Host

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env: 
      RELEASE_PATH: bin/release
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101    
        
    - name: Install dependencies
      run: dotnet restore -s https://api.nuget.org/v3/index.json -s https://nuget.emzi0767.com/api/v3/index.json

    - name: Create executable of HandyHansel
      run: dotnet publish --output ./${{ env.RELEASE_PATH }}/x64/HandyHanselDir --runtime ubuntu.18.04-x64 --source https://api.nuget.org/v3/index.json --source https://nuget.emzi0767.com/api/v3/index.json 
      
    - name: Stop old process using SSH command
      uses: garygrossgarten/github-action-ssh@4641a15616dfd2a3c9205261fe502e45168f2165
      with: 
        command: pkill HandyHansel
        host: ${{ secrets.LINODE_HOST_NAME }}
        username: ${{ secrets.USER_GITHUB_DEPLOY_USERNAME }}
        privatekey: ${{ secrets.USER_GITHUB_DEPLOY_PK }} 
        
    - name: Delete old executable using SSH command
      uses: garygrossgarten/github-action-ssh@4641a15616dfd2a3c9205261fe502e45168f2165
      with: 
        command: cd HandyHansel; rm -rf ./*;
        host: ${{ secrets.LINODE_HOST_NAME }}
        username: ${{ secrets.USER_GITHUB_DEPLOY_USERNAME }}
        privatekey: ${{ secrets.USER_GITHUB_DEPLOY_PK }} 
  
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.1.2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.USER_GITHUB_DEPLOY_PK }}
        ARGS: "-rltgoDzvO"
        SOURCE: ${{ env.RELEASE_PATH }}/x64/HandyHanselDir
        REMOTE_HOST: ${{ secrets.LINODE_HOST_NAME }}
        REMOTE_USER: ${{ secrets.USER_GITHUB_DEPLOY_USERNAME }}
        TARGET: ${{ secrets.TARGET }}
        
    - name: Start new process using SSH command
      uses: garygrossgarten/github-action-ssh@4641a15616dfd2a3c9205261fe502e45168f2165
      with: 
        command: export BOT_TOKEN=${{ secrets.BOT_TOKEN }}; export POSTGRESQL_CONN_STRING=${{ secrets.HANDY_HANSEL_DB_CONN_STRING }}; export DEV_USER_ID=${{ secrets.DEV_USER_ID }}; cd HandyHansel/HandyHanselDir; (exec ./HandyHansel &> /dev/null &);
        host: ${{ secrets.LINODE_HOST_NAME }}
        username: ${{ secrets.USER_GITHUB_DEPLOY_USERNAME }}
        privatekey: ${{ secrets.USER_GITHUB_DEPLOY_PK }} 
